apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: "nginx-1"
spec:
  serviceAccountName: nginx-1
  containers:
    - name: nginx-1
      image: gcr.io/se-kabu/nginx-1:latest
      ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-lb
  labels:
    app: "nginx-1"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "nginx-1"
  type: "LoadBalancer"