apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-3
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  labels:
    app: "nginx-3"
spec:
  serviceAccountName: nginx-3
  containers:
    - name: nginx-3
      image: gcr.io/se-kabu/nginx-3:latest
      ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-3-lb
  labels:
    app: "nginx-3"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "nginx-3"
  type: "LoadBalancer"