apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: "nginx-2"
spec:
  serviceAccountName: nginx-2
  containers:
    - name: nginx-2
      image: gcr.io/se-kabu/nginx-2:latest
      ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-lb
  labels:
    app: "nginx-2"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "nginx-2"
  type: "LoadBalancer"